# Generated by Django 2.2.5 on 2020-02-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_to_json', '0002_csvfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song_contributer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='song_contributer',
            name='contributer',
        ),
        migrations.RemoveField(
            model_name='song_contributer',
            name='song',
        ),
        migrations.DeleteModel(
            name='contributers',
        ),
        migrations.DeleteModel(
            name='song_contributer',
        ),
        migrations.DeleteModel(
            name='songs',
        ),
    ]
